onerror {resume}
quietly WaveActivateNextPane {} 0
add wave -noupdate /system_tb/CLK
add wave -noupdate /system_tb/nRST
add wave -noupdate /system_tb/DUT/CPU/CLK
add wave -noupdate -divider {ram signals}
add wave -noupdate /system_tb/DUT/RAM/ramif/ramREN
add wave -noupdate /system_tb/DUT/RAM/ramif/ramWEN
add wave -noupdate /system_tb/DUT/RAM/ramif/ramaddr
add wave -noupdate /system_tb/DUT/RAM/ramif/ramstore
add wave -noupdate /system_tb/DUT/RAM/ramif/ramload
add wave -noupdate /system_tb/DUT/RAM/ramif/ramstate
add wave -noupdate /system_tb/DUT/RAM/ramif/memREN
add wave -noupdate /system_tb/DUT/RAM/ramif/memWEN
add wave -noupdate /system_tb/DUT/RAM/ramif/memaddr
add wave -noupdate /system_tb/DUT/RAM/ramif/memstore
add wave -noupdate -divider ifif
add wave -noupdate /system_tb/DUT/CPU/DP/ifif/jump_in
add wave -noupdate /system_tb/DUT/CPU/DP/ifif/branchSel_in
add wave -noupdate /system_tb/DUT/CPU/DP/ifif/ihit
add wave -noupdate /system_tb/DUT/CPU/DP/ifif/jumpaddr_in
add wave -noupdate /system_tb/DUT/CPU/DP/ifif/branchaddr_in
add wave -noupdate /system_tb/DUT/CPU/DP/ifif/rdata1_in
add wave -noupdate /system_tb/DUT/CPU/DP/ifif/npc_out
add wave -noupdate /system_tb/DUT/CPU/DP/ifif/imemaddr_out
add wave -noupdate /system_tb/DUT/CPU/DP/ifif/imemload_in
add wave -noupdate /system_tb/DUT/CPU/DP/ifif/imemload_out
add wave -noupdate -divider idif
add wave -noupdate /system_tb/DUT/CPU/DP/idif/npc_in
add wave -noupdate /system_tb/DUT/CPU/DP/idif/npc_out
add wave -noupdate /system_tb/DUT/CPU/DP/idif/imemload_in
add wave -noupdate /system_tb/DUT/CPU/DP/idif/imemload_out
add wave -noupdate /system_tb/DUT/CPU/DP/idif/halt_out
add wave -noupdate /system_tb/DUT/CPU/DP/idif/regWrite_out
add wave -noupdate /system_tb/DUT/CPU/DP/idif/memWrite_out
add wave -noupdate /system_tb/DUT/CPU/DP/idif/memRead_out
add wave -noupdate /system_tb/DUT/CPU/DP/idif/memtoReg_out
add wave -noupdate /system_tb/DUT/CPU/DP/idif/alusrc_out
add wave -noupdate /system_tb/DUT/CPU/DP/idif/jal_out
add wave -noupdate /system_tb/DUT/CPU/DP/idif/jump_out
add wave -noupdate /system_tb/DUT/CPU/DP/idif/regDst_out
add wave -noupdate /system_tb/DUT/CPU/DP/idif/branch_out
add wave -noupdate /system_tb/DUT/CPU/DP/idif/aluOp_out
add wave -noupdate /system_tb/DUT/CPU/DP/idif/rdat1_out
add wave -noupdate /system_tb/DUT/CPU/DP/idif/rdat2_out
add wave -noupdate /system_tb/DUT/CPU/DP/idif/wdatWB_in
add wave -noupdate /system_tb/DUT/CPU/DP/idif/npcWB_in
add wave -noupdate /system_tb/DUT/CPU/DP/idif/regWriteWB_in
add wave -noupdate /system_tb/DUT/CPU/DP/idif/jalWB_in
add wave -noupdate /system_tb/DUT/CPU/DP/idif/regSelWB_in
add wave -noupdate /system_tb/DUT/CPU/DP/idif/imme_out
add wave -noupdate -divider exif
add wave -noupdate /system_tb/DUT/CPU/DP/exif/imemload_in
add wave -noupdate /system_tb/DUT/CPU/DP/exif/npc_in
add wave -noupdate /system_tb/DUT/CPU/DP/exif/rdat1_in
add wave -noupdate /system_tb/DUT/CPU/DP/exif/rdat2_in
add wave -noupdate /system_tb/DUT/CPU/DP/exif/imme_in
add wave -noupdate /system_tb/DUT/CPU/DP/exif/rdat1_out
add wave -noupdate /system_tb/DUT/CPU/DP/exif/rdat2_out
add wave -noupdate /system_tb/DUT/CPU/DP/exif/npc_out
add wave -noupdate /system_tb/DUT/CPU/DP/exif/aluOut_out
add wave -noupdate /system_tb/DUT/CPU/DP/exif/aluOp_in
add wave -noupdate /system_tb/DUT/CPU/DP/exif/ALUsrc_in
add wave -noupdate /system_tb/DUT/CPU/DP/exif/regDst_in
add wave -noupdate /system_tb/DUT/CPU/DP/exif/jal_in
add wave -noupdate /system_tb/DUT/CPU/DP/exif/branch_in
add wave -noupdate /system_tb/DUT/CPU/DP/exif/memtoReg_in
add wave -noupdate /system_tb/DUT/CPU/DP/exif/jump_in
add wave -noupdate /system_tb/DUT/CPU/DP/exif/regWrite_in
add wave -noupdate /system_tb/DUT/CPU/DP/exif/jumpaddr_out
add wave -noupdate /system_tb/DUT/CPU/DP/exif/branchaddr_out
add wave -noupdate /system_tb/DUT/CPU/DP/exif/branchSel_out
add wave -noupdate /system_tb/DUT/CPU/DP/exif/jump_out
add wave -noupdate /system_tb/DUT/CPU/DP/exif/jal_out
add wave -noupdate /system_tb/DUT/CPU/DP/exif/memtoReg_out
add wave -noupdate /system_tb/DUT/CPU/DP/exif/regWrite_out
add wave -noupdate /system_tb/DUT/CPU/DP/exif/regSel_out
add wave -noupdate /system_tb/DUT/CPU/DP/exif/halt_in
add wave -noupdate /system_tb/DUT/CPU/DP/exif/memRead_in
add wave -noupdate /system_tb/DUT/CPU/DP/exif/memWrite_in
add wave -noupdate -divider memif
add wave -noupdate /system_tb/DUT/CPU/DP/memif/jump_in
add wave -noupdate /system_tb/DUT/CPU/DP/memif/jump_out
add wave -noupdate /system_tb/DUT/CPU/DP/memif/branchSel_in
add wave -noupdate /system_tb/DUT/CPU/DP/memif/branchSel_out
add wave -noupdate /system_tb/DUT/CPU/DP/memif/branchaddr_in
add wave -noupdate /system_tb/DUT/CPU/DP/memif/branchaddr_out
add wave -noupdate /system_tb/DUT/CPU/DP/memif/jumpaddr_in
add wave -noupdate /system_tb/DUT/CPU/DP/memif/jumpaddr_out
add wave -noupdate /system_tb/DUT/CPU/DP/memif/npc_in
add wave -noupdate /system_tb/DUT/CPU/DP/memif/npc_out
add wave -noupdate /system_tb/DUT/CPU/DP/memif/rdat1_in
add wave -noupdate /system_tb/DUT/CPU/DP/memif/rdat1_out
add wave -noupdate /system_tb/DUT/CPU/DP/memif/aluOut_in
add wave -noupdate /system_tb/DUT/CPU/DP/memif/aluOut_out
add wave -noupdate /system_tb/DUT/CPU/DP/memif/dmemaddr_out
add wave -noupdate /system_tb/DUT/CPU/DP/memif/dmemstore_in
add wave -noupdate /system_tb/DUT/CPU/DP/memif/dmemstore_out
add wave -noupdate /system_tb/DUT/CPU/DP/memif/dmemload_in
add wave -noupdate /system_tb/DUT/CPU/DP/memif/dmemload_out
add wave -noupdate /system_tb/DUT/CPU/DP/memif/memtoReg_in
add wave -noupdate /system_tb/DUT/CPU/DP/memif/memtoReg_out
add wave -noupdate /system_tb/DUT/CPU/DP/memif/jal_in
add wave -noupdate /system_tb/DUT/CPU/DP/memif/jal_out
add wave -noupdate /system_tb/DUT/CPU/DP/memif/regWrite_in
add wave -noupdate /system_tb/DUT/CPU/DP/memif/regWrite_out
add wave -noupdate /system_tb/DUT/CPU/DP/memif/regSel_in
add wave -noupdate /system_tb/DUT/CPU/DP/memif/regSel_out
add wave -noupdate /system_tb/DUT/CPU/DP/memif/halt_out
add wave -noupdate /system_tb/DUT/CPU/DP/memif/memWrite_out
add wave -noupdate /system_tb/DUT/CPU/DP/memif/memRead_out
add wave -noupdate -divider wbif
add wave -noupdate /system_tb/DUT/CPU/DP/wbif/memtoReg_in
add wave -noupdate /system_tb/DUT/CPU/DP/wbif/jal_in
add wave -noupdate /system_tb/DUT/CPU/DP/wbif/jal_out
add wave -noupdate /system_tb/DUT/CPU/DP/wbif/regWrite_in
add wave -noupdate /system_tb/DUT/CPU/DP/wbif/regWrite_out
add wave -noupdate /system_tb/DUT/CPU/DP/wbif/regSel_in
add wave -noupdate /system_tb/DUT/CPU/DP/wbif/regSel_out
add wave -noupdate /system_tb/DUT/CPU/DP/wbif/dmemload_in
add wave -noupdate /system_tb/DUT/CPU/DP/wbif/aluOut_in
add wave -noupdate /system_tb/DUT/CPU/DP/wbif/wdat_out
add wave -noupdate /system_tb/DUT/CPU/DP/wbif/npc_in
add wave -noupdate /system_tb/DUT/CPU/DP/wbif/npc_out
add wave -noupdate -divider rfif
add wave -noupdate /system_tb/DUT/CPU/DP/sid/rfif/WEN
add wave -noupdate /system_tb/DUT/CPU/DP/sid/rfif/wsel
add wave -noupdate /system_tb/DUT/CPU/DP/sid/rfif/rsel1
add wave -noupdate /system_tb/DUT/CPU/DP/sid/rfif/rsel2
add wave -noupdate /system_tb/DUT/CPU/DP/sid/rfif/wdat
add wave -noupdate /system_tb/DUT/CPU/DP/sid/rfif/rdat1
add wave -noupdate /system_tb/DUT/CPU/DP/sid/rfif/rdat2
add wave -noupdate -expand /system_tb/DUT/CPU/DP/sid/rfid/register
add wave -noupdate -divider dpif
add wave -noupdate /system_tb/DUT/CPU/DP/dpif/halt
add wave -noupdate /system_tb/DUT/CPU/DP/dpif/ihit
add wave -noupdate /system_tb/DUT/CPU/DP/dpif/imemREN
add wave -noupdate /system_tb/DUT/CPU/DP/dpif/imemload
add wave -noupdate /system_tb/DUT/CPU/DP/dpif/imemaddr
add wave -noupdate /system_tb/DUT/CPU/DP/dpif/dhit
add wave -noupdate /system_tb/DUT/CPU/DP/dpif/datomic
add wave -noupdate /system_tb/DUT/CPU/DP/dpif/dmemREN
add wave -noupdate /system_tb/DUT/CPU/DP/dpif/dmemWEN
add wave -noupdate /system_tb/DUT/CPU/DP/dpif/flushed
add wave -noupdate /system_tb/DUT/CPU/DP/dpif/dmemload
add wave -noupdate /system_tb/DUT/CPU/DP/dpif/dmemstore
add wave -noupdate /system_tb/DUT/CPU/DP/dpif/dmemaddr
add wave -noupdate -divider hdif
add wave -noupdate /system_tb/DUT/CPU/DP/hdif/stall
add wave -noupdate /system_tb/DUT/CPU/DP/hdif/flush_if
add wave -noupdate /system_tb/DUT/CPU/DP/hdif/flush_id
add wave -noupdate /system_tb/DUT/CPU/DP/hdif/flush_ex
add wave -noupdate /system_tb/DUT/CPU/DP/hdif/branchSel
add wave -noupdate /system_tb/DUT/CPU/DP/hdif/jump
add wave -noupdate /system_tb/DUT/CPU/DP/hdif/memRead_ex
add wave -noupdate /system_tb/DUT/CPU/DP/hdif/rt_ex
add wave -noupdate /system_tb/DUT/CPU/DP/hdif/imemload_id
add wave -noupdate -divider fuif
add wave -noupdate /system_tb/DUT/CPU/DP/fuif/regSel_mem
add wave -noupdate /system_tb/DUT/CPU/DP/fuif/regSel_wb
add wave -noupdate /system_tb/DUT/CPU/DP/fuif/regWrite_mem
add wave -noupdate /system_tb/DUT/CPU/DP/fuif/regWrite_wb
add wave -noupdate /system_tb/DUT/CPU/DP/fuif/rs_ex
add wave -noupdate /system_tb/DUT/CPU/DP/fuif/rt_ex
add wave -noupdate /system_tb/DUT/CPU/DP/fuif/portaSel
add wave -noupdate /system_tb/DUT/CPU/DP/fuif/portbSel
TreeUpdate [SetDefaultTree]
WaveRestoreCursors {{Cursor 1} {1179456 ps} 0}
quietly wave cursor active 1
configure wave -namecolwidth 150
configure wave -valuecolwidth 80
configure wave -justifyvalue left
configure wave -signalnamewidth 1
configure wave -snapdistance 10
configure wave -datasetprefix 0
configure wave -rowmargin 4
configure wave -childrowmargin 2
configure wave -gridoffset 0
configure wave -gridperiod 1
configure wave -griddelta 40
configure wave -timeline 0
configure wave -timelineunits ns
update
WaveRestoreZoom {0 ps} {2476256 ps}
